"""create bom_items and routing_steps tables

Revision ID: d40b7312a499
Revises: 98cb02e687eb
Create Date: 2026-07-08 12:00:50.860189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40b7312a499'
down_revision: Union[str, Sequence[str], None] = '98cb02e687eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_product_id', sa.UUID(), nullable=False),
    sa.Column('child_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['child_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('standard_time_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_steps')
    op.drop_table('bom_items')
    # ### end Alembic commands ###
